### ISSUE TITLE
Crashes while getting collection ready

### ISSUE THREAD

**Issue by DarkEcho3s** [TyJOrtiz/Mustastic#1]
The app will crash after about 30 seconds of the "Getting your collection ready" screen. Have tried re-installing the app, and rebooting my computer.

**Comment by TyJOrtiz** [comment]
What is your system configuration?

**Comment by DarkEcho3s** [comment]
Windows 10 Pro 20H2 (build 19042.610)
Ryzen 9 3900XT
32GB RAM
GTX 1080 Ti
Seagate Firecude 520 SSD

**Comment by TyJOrtiz** [comment]
Do you have OneDrive music folders in your music library? Or maybe recordings? I just need to know to recreate those scenarios

**Comment by DarkEcho3s** [comment]
No for both. My Music folder is local and contains two folders:

1) iTunes folder
2) A folder called "Music" where I have all my local music media organized.

**Comment by TyJOrtiz** [comment]
Can you please open Event Viewer, go to "windows logs" -> "Application" and Click "find" and type "NewMusicProject" and find the eroor event that was at the time of the crash and let me now what it says?

**Comment by DarkEcho3s** [comment]
Yes, here are the details:

Application Error, Event ID 1000

Faulting application name: NewMusicProject.exe, version: 1.0.0.0, time stamp: 0x5f9bef26
Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x1183946c
Exception code: 0xc000027b
Fault offset: 0x000000000010b65c
Faulting process id: 0x57fc
Faulting application start time: 0x01d6b12e8419c004
Faulting application path: C:\Program Files\WindowsApps\2a036d42-5cca-4631-bfad-531aa9f6b94c_1.0.1.0_x64__2wr0nn36e1wmy\NewMusicProject.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: cdc24f5a-ce2a-4192-b0fd-8434e0023de7
Faulting package full name: 2a036d42-5cca-4631-bfad-531aa9f6b94c_1.0.1.0_x64__2wr0nn36e1wmy
Faulting package-relative application ID: App

**Comment by TyJOrtiz** [comment]
I'm going to release another update through, hopefully it will be solved; I can't tell what's going wrong because it's been running fine on my end on different devices.

**Comment by DarkEcho3s** [comment]
I did some further troubleshooting using two different computers that I have, and the results below are the same on both computers:

- If the Music folder is empty, the app runs fine.
- If the Music folder has a handful of albums in it, the app runs fine and sees the music.
- If the Music folder has just my music in it (not the iTunes folder) the app crashes after about 30 seconds (I can see the memory usage of the app increasing so it looks like it's at least trying to load). My music folder has about 90GB of music files in it.
- If the Music folder has just my iTunes folder in it the app loads but doesn't see any music, as the only music that is in the iTunes folder is Apple Music downloads.

**Comment by TyJOrtiz** [comment]
@DarkEcho3s Thanks for pointing this out to me, I will optimize the code and have file enumeration in blocks instead as opposed to having them all loaded. Hopefully this will be better for memory

**Comment by TyJOrtiz** [comment]
@DarkEcho3s I'll have a new package ready in about an hour

**Comment by DarkEcho3s** [comment]
Awesome, I'll keep an eye out for it.

**Comment by TyJOrtiz** [comment]
Ok it's released, Version 1.0.3.0

**Comment by DarkEcho3s** [comment]
Uninstalled the old version and installed the new version, but am encountering a different issue now. The app just perpetually sits at the "Getting your collection ready" screen. I left it for about 4 hours and it was still on that screen. Nothing in the Event Viewer regarding the app. Also noticed the memory usage of the app tops out at about 160MB. I'm wondering if the size of my music collection is causing issues with it?

**Comment by TyJOrtiz** [comment]
The memory usage is fine, to keep memory usage down I have the app taking the user's albums in chunks of 20, it takes less than 2 minutes or so on my machine and I have 380 albums (6 GB). How many songs would you say you have?

**Comment by DarkEcho3s** [comment]
I have about 15,000 songs (90GB) in my library.

**Comment by TyJOrtiz** [comment]
I think it might be the collection size. I'm gonna do some more experimenting

**Comment by TyJOrtiz** [comment]
I've created a new update which does a way better job of monitoring the progress. I'll have it up in about an hour and a half at latest.

**Comment by TyJOrtiz** [comment]
I uploaded a new release (1.0.11.0) https://github.com/TyJOrtiz/Mustastic/releases/tag/1.0.11.0

**Comment by luandersonn** [comment]
I'm stuck here
![image](https://user-images.githubusercontent.com/30560453/100161192-ba8dfa80-2e8f-11eb-8454-00e88599c8ef.png)

**Comment by TyJOrtiz** [comment]
i uploaded a new version under releases. Let me know what it gets stuck on

**Comment by DarkEcho3s** [comment]
Installed the newest version. Looks like mine is stopping at .m4v and .m4a files.

**Comment by TyJOrtiz** [comment]
Thank you, I'm going to revise my code.

**Comment by TyJOrtiz** [comment]
@luandersonn @DarkEcho3s I'm pushing an update to the Store that'll hopefully resolve this.

**Comment by luandersonn** [comment]
@TyJOrtiz  Still

**Comment by TyJOrtiz** [comment]
@luandersonn the update hasn't been released yet

**Comment by luandersonn** [comment]
@TyJOrtiz ooh, ok...

**Comment by TyJOrtiz** [comment]
@luandersonn the update is in the store

**Comment by luandersonn** [comment]
@TyJOrtiz  Thanks, It works now. But some albums are duplicated

![image](https://user-images.githubusercontent.com/30560453/101380111-e055cf00-3893-11eb-9558-c07bbcd863a9.png)

**Comment by luandersonn** [comment]
**Update**
I just refreshed the library, now everything is fine.

**Comment by TyJOrtiz** [comment]
I'm gonna check that out because it shouldn't be doing that at all, obviously.

**Comment by TyJOrtiz** [comment]
> **Update**
> 
> I just refreshed the library, now everything is fine.

Oh ok
