### ISSUE TITLE
Allow click outside of album tracklist preview popup to close it

### ISSUE THREAD

**Issue by LolicoreExpress** [TyJOrtiz/Mustastic#11]
**Is your feature request related to a problem? Please describe.**
Clicking outside of the popup does not close it, which is expected behavior for me, but maybe that's just me.

**Describe the solution you'd like**
A click outside of the popup, in the grey-out area (but still inside the program window, obviously), closes the popup. 
Same effect as clicking on the Close button.

**Additional context**
![Screenshot](https://user-images.githubusercontent.com/29737484/110231951-fb7bbd80-7f1a-11eb-8241-a36c24a8ace7.png)
Let me click the greyed-out area to close please ^^

**Comment by TyJOrtiz** [comment]
Definitely in progress, 

I'm trying to work that feature out, if it's possible it will be in a future update.

**Comment by TyJOrtiz** [comment]
I figured it out, it'll arrive with the next update

**Comment by LolicoreExpress** [comment]
Awesome, thank you 😄

**Comment by LolicoreExpress** [comment]
Thank you for implementing that. I'm closing the issue.
