### ISSUE TITLE
Left sidebar state is not remembered after closing and reopening

### ISSUE THREAD

**Issue by LolicoreExpress** [TyJOrtiz/Mustastic#12]
**Describe the bug**
The state of the left sidebar is not being remembered after closing and reopening the program. 

**To Reproduce**
1. Open the program.
2. Collapse the sidebar by clicking the collapse button.
3. Close the program.
4. Launch the program again and see the sidebar is expanded again.

**Expected behavior**
Sidebar's collapsed or expanded state should be remembered after closing and reopening the program.

**Screenshots**
https://files.catbox.moe/8fmexz.webm

**Desktop (please complete the following information):**
 - Windows 10 Education 20H2 update, v19042.844
 - x64
 - 16 gigs of RAM

**Additional context**
Maybe this is not a bug but rather the intended behavior.  My bad if that's the case !

**Comment by TyJOrtiz** [comment]
This will be addressed in the next update.

Thank you for your feedback :)

**Comment by LolicoreExpress** [comment]
Great, it works now, thank you :)
