### ISSUE TITLE
Audio skips randomly during playback

### ISSUE THREAD

**Issue by LolicoreExpress** [TyJOrtiz/Mustastic#13]
**Describe the bug**
During normal playback, audio will skip a couple seconds forward (or even backwards sometimes, I feel). It happens to me maybe once per minute, but it's still pretty random.

**To Reproduce**
1. Play a song for a couple minutes
2. Notice the "skip" in audio during playback

**Expected behavior**
No audio skips during playback, obviously :p

**Screenshots**
I captured some audio of what it sounds like when it happens.
Here's example n°1: https://files.catbox.moe/653ml0.mp3
And here's n°2: https://files.catbox.moe/m60ei1.mp3
It's easier to hear in n°2. But I think you'll clearly here the moment it cuts and skips.

**Desktop (please complete the following information):**
 - Windows 10 Education 20H2 build 19042.867
 - x86 architecture
 - 16 Gigs of RAM

**Additional context**
It's hard to tell, but it seems to happen less when I'm not playing a game at the same time. So it might be related to heavy hard drive utilization when I'm playing a game ?

**Comment by TyJOrtiz** [comment]
Hi, 

I noticed that behavior as well.

I've simplified a lot of the code (as it was relying on a bunch of timers and things like that) so I'm just running tests right now)

**Comment by LolicoreExpress** [comment]
Seems to be gone completely after latest update. Great work 👌
