### ISSUE TITLE
Wrong play/pause button in compact player when opened while a song is playing

### ISSUE THREAD

**Issue by LolicoreExpress** [TyJOrtiz/Mustastic#15]
**Describe the bug**
When you start playing a song, and then enter compact mode, the button displayed at first on the compact player is "play" when it should be "pause" (since there is a song playing). If you click it, it returns to normal behavior, it's just when first entering compact player.

**To Reproduce**
1. Start playing a song
2. Switch to compact player
3. Notice the button being is "play" rather than "pause"

**Expected behavior**
The button displayed when first entering compact player while a song is playing should be "pause".

**Screenshots**
![Capture d’écran 2021-04-19 225254](https://user-images.githubusercontent.com/29737484/115303112-7dd6de80-a163-11eb-8276-092a07a25754.png)
Here, I just entered compact player while playing a song and you can see the problem.

**Desktop (please complete the following information):**
 - Windows 10 20H2 v.19042.928 Windows Feature Experience Pack 120.2212.551.0
 - x64
 - 16 GB

**Comment by TyJOrtiz** [comment]
The issue will be fixed in the next update.

Thanks for your feedback 🙂
