### ISSUE TITLE
Space out the grid view when selecting a genre

### ISSUE THREAD

**Issue by LolicoreExpress** [TyJOrtiz/Mustastic#16]
**Is your feature request related to a problem? Please describe.**
The grid view to select a letter or genre or date, is not spaced out enough for text to be fully displayed. 

**Describe the solution you'd like**
Let's space it out a little :)

**Additional context**
![Capture d’écran 2021-05-03 172539](https://user-images.githubusercontent.com/29737484/116897095-2b062800-ac35-11eb-91ec-3f645ce2adbe.png)
![Capture d’écran 2021-05-03 172722](https://user-images.githubusercontent.com/29737484/116897098-2b062800-ac35-11eb-851d-cf7ca5619a68.png)

**Comment by TyJOrtiz** [comment]
![image](https://user-images.githubusercontent.com/25320332/116915803-5e2ec400-ac01-11eb-9e47-30d1b15d2468.png)

It'll be fixed in the next update.

Thank you for your feedback :)

**Comment by LolicoreExpress** [comment]
Great. Thank you !
