### ISSUE TITLE
Unsmooth transitions on the background+shadow of the player bar

### ISSUE THREAD

**Issue by LolicoreExpress** [TyJOrtiz/Mustastic#18]
**Describe the bug**
On the Now Playing view, you can see the transitions visibly happening in two times, and not at the same time. Ain't a huge problem or anything but it doesn't look too good.

**Expected behavior**
They happen in one go, all pretty and smooth 👍 

**Screenshots**
https://files.catbox.moe/odeh04.webm

**Comment by TyJOrtiz** [comment]
This will be fixed in the next update.

Thank you for your feedback :)

**Comment by LolicoreExpress** [comment]
Great, thank you.
