### ISSUE TITLE
Get a ARTIST tag displayed on the Now Playing view (currently only ALBUM ARTIST)

### ISSUE THREAD

**Issue by LolicoreExpress** [TyJOrtiz/Mustastic#20]
Currently only the ALBUM ARTIST tag is displayed under the cover art in the Now Playing view.
So especially for compilations and multi artists works, if you tend to tag them as ALBUM ARTIST="Various Artists" like me, then you just get a nice "Various Artists" under every song in the album when really I want to see the ARTIST tag of each song.

**Describe the solution you'd like**
Add a line for the ARTIST tag in the track info under the cover art.

**Comment by TyJOrtiz** [comment]
I fixed this, it'll be in the next update.

**Comment by LolicoreExpress** [comment]
Awesome, ahead of the curve as always 😁
