### ISSUE TITLE
Edited tags on an album, it updated the Date Added when it shouldn't have

### ISSUE THREAD

**Issue by LolicoreExpress** [TyJOrtiz/Mustastic#22]
**Describe the bug**
I had added an album to my collection some weeks ago, and thanks to the recent update, it's Add Date was properly recognized and everything was fine. However, I was doing some tag editing on some albums, and the Add Date for one of them got changed to today even though I didn't move it in-n-out of my music folder or anything, just edited some tags and it modified the Add Date for some reason, from being marked as added some weeks ago, to marked as added today.

**To Reproduce**
No real steps except try and modify tags here and there. 
I've tried to reproduce it myself by modifying various tags on albums I added some time ago, but I didn't manage to reproduce.

**Expected behavior**
More reliable Add Date recognition.

**Desktop (please complete the following information):**
 - Windows 10 21H1, Build 19043.1023, Windows Feature Experience Pack 120.2212.2020.0
 - x64
 - 16GB of RAM

**Additional context**
Since I have no idea how you work out that Add Date recognition within Mustatic, I don't know if it's something I've done myself that caused it not. Could modifying the name of the folder of the album cause the bug, for example ? Could changing tags that were in Latin characters to Japanese characters cause that ? I don't know.

**Comment by TyJOrtiz** [comment]
The app takes the “Date created” property to sort albums by date. I don’t know if the issue you’re having is an OS issue:

https://answers.microsoft.com/en-us/windows/forum/windows_10-files/original-date-created-is-changed-every-time-i/2ef69d34-7563-4d79-b56f-73cdf144fb9f

**Comment by LolicoreExpress** [comment]
You're right, this person's issue seem to be exactly like what I'm experiencing.
I just checked, and the Date Created property of my album's files was updated to match the Date Modified property.
I also have my music collection on a different drive than my Windows drive.

So this is a Windows bug... Well, nothing we can do about that, sadly.
Thanks !
