### ISSUE TITLE
radio

### ISSUE THREAD

**Issue by senolfndk** [TyJOrtiz/Mustastic#31]

**Comment by TyJOrtiz** [comment]
> can you add radio play feature if possible

I'll see if that's something I can implement and will update you accordingly

**Comment by senolfndk** [comment]
when will you update

**Comment by TyJOrtiz** [comment]
I will send an update in the coming months. I’ve had to start the project over from scratch.

WIlliam

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by senolfndk** [comment]
> Önümüzdeki aylarda bir güncelleme göndereceğim. Projeye sıfırdan başlamak zorunda kaldım. WIlliam Mail'den Gönderildi< https://go.microsoft.com/fwlink/?LinkId=550986 > Windows için Kimden: şenol ***@***.***> Gönderildi: 7 Ağustos 2022 Pazar 10:59 AM Alıcı: ***@***.***> Bilgi: Tyler ***@***.***>; Durum ***@***.***> Konu: Re: [TyJOrtiz/Mustastic] radyo (Sayı #31 ) ne zaman güncelleme yapacaksınız — Bu e-postayı doğrudan yanıtlayın, GitHub'da görüntüleyin<[https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTyJOrtiz%2FMustastic%2Fissues%2F3%23issuecomment-1207456810&data=05%7C01%7C%7Ca0a7590d56bf49f897bfe4aaaaaaaa9%7C87e9508%2Fissues%2F3%23issuecomment %7C0%7C637954919762544899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ibcJ9ZXCbwOFqhK3KC5RKkAIClZS9zoGp%2FMssBHiWVw%3D&reserved=0](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTyJOrtiz%2FMustastic%2Fissues%2F31%23issuecomment-1207456810&data=05%7C01%7C%7Ca0a7590d56bf49f8705408da789e95cf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637954919762544899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ibcJ9ZXCbwOFqhK3KC5RKkAIClZS9zoGp%2FMssBHiWVw%3D&reserved=0) >, or unsubscribe<[https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGBFXDHYCPWSAZZUPDX3VZDVX72QLANCNFSM5RC3Q5BQ&data=05%7C01%7C%7Ca0a7590d56bf49f8705408da789e95cf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637954919762564806 %7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aAS5ahzRXAIh3BH7C%7C&sdata=aAS5ahzRX%](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGBFXDHYCPWSAZZUPDX3VZDVX72QLANCNFSM5RC3Q5BQ&data=05%7C01%7C%7Ca0a7590d56bf49f8705408da789e95cf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637954919762564806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aAS5ahzRXAIhvkj0dYmSS77L3N7gBmBgHhKyjHD3njA%3D&reserved=0) 77 Bunu, açma/kapama durumunu değiştirdiğiniz için alıyorsunuz.Mesaj Kimliği: ***@***.***>

ok

**Comment by senolfndk** [comment]
How are you my friend? Are you continuing the project?

**Comment by TyJOrtiz** [comment]
Hi,

Message ID: ***@***.***>

Yes I am. I ran into a couple snags so it will be finished early next year

**Comment by senolfndk** [comment]
> Merhaba, Mesaj Kimliği: ***@***.***> Evet öyleyim. Birkaç engelle karşılaştım, o yüzden gelecek yılın başlarında bitecek

ok
