### ISSUE TITLE
kütüphane

### ISSUE THREAD

**Issue by senolfndk** [TyJOrtiz/Mustastic#4]
![SharedScreenshot](https://user-images.githubusercontent.com/52818836/100790107-6901e480-3428-11eb-8029-e5a9b481710d.jpg)
not progressing

**Comment by TyJOrtiz** [comment]
I'm looking for a fix for this

**Comment by TyJOrtiz** [comment]
Mağazaya bir güncelleme yüklüyorum. Yarına kadar hazır olur. Umarım sorunu çözer.

**Comment by TyJOrtiz** [comment]
Theres a new update in the store, please update Mustastic
