### ISSUE TITLE
Import .m3u playlists

### ISSUE THREAD

**Issue by Lambada10** [TyJOrtiz/Mustastic#7]
**Describe the solution you'd like**
Importing playlists from .m3u files. Import from file button in the playlist tab

**Describe alternatives you've considered**
Opening .m3u file in Mustastic will cause importing it automatically

**Comment by TyJOrtiz** [comment]
Im working on m3u functionality right now :)

**Comment by TyJOrtiz** [comment]
.m3u functionality is now in the app (i forgot to mention; I'm going to close this issue)
