### ISSUE TITLE
Use System Accent color (Option)

### ISSUE THREAD

**Issue by Neptune-mk2** [TyJOrtiz/Mustastic#8]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to a problem.

**Describe the solution you'd like**
I feel the app should use the system accent color that is selected by the user instead of default blue.

**Describe alternatives you've considered**
If for whatever reason the app requires the default color be default blue, please consider adding the option to use the system accent color as a optional setting that can be toggled on/off.

**Additional context**
I'm very intrigued by your app, I've been looking for a new  UWP based music player, and this looks to have immense potential, as a advocate for robust theming I hope with time the app gains more customization options.

**Comment by TyJOrtiz** [comment]
Hi,

Adding support for custom/system accent colors is defintiely in the feature roadmap, I've just been trying to find out how to change them dynamically for a while now lol. Microsoft doesn't give a lot of info on how to do that.

**Comment by TyJOrtiz** [comment]
I think I'm just going to remove the blue accent color and leave it to the system

**Comment by Neptune-mk2** [comment]
> I think I'm just going to remove the blue accent color and leave it to the system

Good to hear!

By the way if your looking for resources or help with anything UWP I would absolutely recommend you consider joining the UWP Community on Discord, that's actually where someone recommended your app to me.

**Comment by TyJOrtiz** [comment]
Thanks, I’m already on there so I’ll see if I can get some help with this

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
